"""empty message

Revision ID: 05e411bbcccb
Revises: d1e1ccdebc92
Create Date: 2025-08-27 23:47:49.040863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e411bbcccb'
down_revision = 'd1e1ccdebc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=False))
        batch_op.drop_column('charact_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charact_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###
