"""empty message

Revision ID: 411c262b569b
Revises: 7c5aad1379a6
Create Date: 2025-08-27 23:42:27.994550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411c262b569b'
down_revision = '7c5aad1379a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_character_character_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.create_foreign_key('favorite_character_character_id_fkey', 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###
