"""empty message

Revision ID: b0722407af04
Revises: 56ccfcf51a67
Create Date: 2025-09-01 19:21:21.051311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0722407af04'
down_revision = '56ccfcf51a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.drop_column('Name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
