"""empty message

Revision ID: e9ae41334e97
Revises: e3740753629e
Create Date: 2025-08-27 23:51:13.849168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ae41334e97'
down_revision = 'e3740753629e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_character_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('userid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favorite_character_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
