"""empty message

Revision ID: f00f73f78ca0
Revises: 83ab10870985
Create Date: 2025-08-27 23:09:49.686281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00f73f78ca0'
down_revision = '83ab10870985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(), nullable=False))
        batch_op.drop_constraint('favorite_character_character_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_character_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('character_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favorite_character_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorite_character_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.drop_column('skin_color')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
